# SPDX-FileCopyrightText: Thomas Breitner
#
# SPDX-License-Identifier: EUPL-1.2

site_name: zammd-kb-export
docs_dir: dist/docs
site_dir: dist/site
plugins:
  - search
  - tags:
      tags: true
      tags_file: tags.md
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          build: true
        - locale: de
          name: Deutsch
          build: true
          default: true
theme:
  name: material
  features:
    - navigation.tabs
